# Generated by Django 5.0.7 on 2024-07-30 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_alter_split_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='split',
            name='expense',
        ),
    ]
