# Generated by Django 5.0.7 on 2024-07-30 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_remove_split_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='split',
            name='expense',
            field=models.ForeignKey(default=200, on_delete=django.db.models.deletion.CASCADE, to='expense.expense'),
            preserve_default=False,
        ),
    ]
