# Generated by Django 5.0.7 on 2024-07-30 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_split_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='split',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split', to='expense.expense'),
        ),
        migrations.AlterField(
            model_name='split',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_split', to=settings.AUTH_USER_MODEL),
        ),
    ]
